In [12]:
import pandas as pd

# Load the Excel file into a DataFrame
file_path = 'Final Candidate Protiens from Research.xlsx'
df_candidates = pd.read_excel(file_path)

In [13]:
df_candidates

,Protien Number,Sequences,Protien Description,Species,Article,Full Sequence
0,WP_014165385,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,IKKYEPAPV
1,WP_107317750,MKKILALFSLFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
2,WP_195157289,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
3,WP_065213479,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
4,WP_105196548,MKKLLTLFSLFLCAEQIQAQSYIGFVPDNYSGVHGMIYNPAAIVGS...,MULTISPECIES: DUF5723 family protein [Flavobac...,Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
...,...,...,...,...,...,...
93,AJE37222.1,MRDTTQVRAMDDYFHSLLLDDALLLDSSDEPDSAPVIQLQRQPQPV...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
94,AJE37560.1,MEKVIFKRAALSAAIVAAMLAPGMVLAADEAGPTYAAAASKFYEEG...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
95,AJE37735.1,MRNLTLLSLGLLAANAAHADLGEIPKQSGWSGFLLGGVNAVSYKSN...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
96,AJE37742.1,MFKANGKGNAVRLVLSVATVAVLAACSSPQERKMANRGFEYEDARL...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
97,AJE38071.1,MLKRITLIALLATTTATTLSGCANSDVYSGDVYTKDRAKQVQTVSY...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN

In [14]:
# Count rows with FASTA header (sequences that contain lines starting with '>')
fasta_header_count = df_candidates['Sequences'].apply(lambda x: any(line.startswith('>') for line in str(x).splitlines())).sum()
print(f"Number of sequences with FASTA headers: {fasta_header_count}")

Number of sequences with FASTA headers: 11

In [15]:

# Remove FASTA header lines, keeping only the sequences
df_candidates['Sequences'] = df_candidates['Sequences'].apply(lambda x: '\n'.join(line for line in str(x).splitlines() if not line.startswith('>')))

# Display the cleaned DataFrame
print(df_candidates[['Protien Number', 'Sequences']].head())

  Protien Number                                          Sequences
0   WP_014165385  MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
1   WP_107317750  MKKILALFSLFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
2   WP_195157289  MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
3   WP_065213479  MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
4   WP_105196548  MKKLLTLFSLFLCAEQIQAQSYIGFVPDNYSGVHGMIYNPAAIVGS...

In [16]:
# Remove empty rows from the DataFrame
df_candidates = df_candidates.dropna(how='all')

# Save the cleaned DataFrame to a CSV file
df_candidates.to_csv('cleaned_candidates.csv', index=False)

In [20]:
df_vaccine_candidate = pd.read_csv('cleaned_candidates.csv')
df_vaccine_candidate

,Protien Number,Sequences,Protien Description,Species,Article,Full Sequence
0,WP_014165385,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,IKKYEPAPV
1,WP_107317750,MKKILALFSLFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
2,WP_195157289,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
3,WP_065213479,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
4,WP_105196548,MKKLLTLFSLFLCAEQIQAQSYIGFVPDNYSGVHGMIYNPAAIVGS...,MULTISPECIES: DUF5723 family protein [Flavobac...,Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
...,...,...,...,...,...,...
93,AJE37222.1,MRDTTQVRAMDDYFHSLLLDDALLLDSSDEPDSAPVIQLQRQPQPV...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
94,AJE37560.1,MEKVIFKRAALSAAIVAAMLAPGMVLAADEAGPTYAAAASKFYEEG...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
95,AJE37735.1,MRNLTLLSLGLLAANAAHADLGEIPKQSGWSGFLLGGVNAVSYKSN...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
96,AJE37742.1,MFKANGKGNAVRLVLSVATVAVLAACSSPQERKMANRGFEYEDARL...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN
97,AJE38071.1,MLKRITLIALLATTTATTLSGCANSDVYSGDVYTKDRAKQVQTVSY...,NaN,Aeromonas hydrophila,The Screening of the Protective Antigens of Ae...,NaN

In [21]:
# Remove rows with NaN values in the 'Protien Number' column
df_vaccine_candidate = df_vaccine_candidate.dropna(subset=['Protien Number']).reset_index(drop=True)

# Remove newline characters within the sequences using .loc to avoid warnings
df_vaccine_candidate.loc[:, 'Sequences'] = df_vaccine_candidate['Sequences'].str.replace('\n', '', regex=True)

# Save the cleaned DataFrame to a new CSV file
df_vaccine_candidate.to_csv('cleaned_vaccine_candidates.csv', index=False)

# Display the cleaned DataFrame
print(df_vaccine_candidate)

   Protien Number                                          Sequences  \
0    WP_014165385  MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
1    WP_107317750  MKKILALFSLFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
2    WP_195157289  MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
3    WP_065213479  MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...
4    WP_105196548  MKKLLTLFSLFLCAEQIQAQSYIGFVPDNYSGVHGMIYNPAAIVGS...
..            ...                                                ...
87     AJE37222.1  MRDTTQVRAMDDYFHSLLLDDALLLDSSDEPDSAPVIQLQRQPQPV...
88     AJE37560.1  MEKVIFKRAALSAAIVAAMLAPGMVLAADEAGPTYAAAASKFYEEG...
89     AJE37735.1  MRNLTLLSLGLLAANAAHADLGEIPKQSGWSGFLLGGVNAVSYKSN...
90     AJE37742.1  MFKANGKGNAVRLVLSVATVAVLAACSSPQERKMANRGFEYEDARL...
91     AJE38071.1  MLKRITLIALLATTTATTLSGCANSDVYSGDVYTKDRAKQVQTVSY...

                                  Protien Description  \
0   DUF5723 family protein [Flavobacterium columnare]
1   DUF5723 family protein [Flavobacterium columnare]
2   DUF5723 family protein [Flavobacterium columnare]
3   DUF5723 family protein [Flavobacterium columnare]
4   MULTISPECIES: DUF5723 family protein [Flavobac...
..                                                ...
87                                                NaN
88                                                NaN
89                                                NaN
90                                                NaN
91                                                NaN

                      Species  \
0    Flavobacterium columnare
1    Flavobacterium columnare
2    Flavobacterium columnare
3    Flavobacterium columnare
4    Flavobacterium columnare
..                        ...
87       Aeromonas hydrophila
88       Aeromonas hydrophila
89       Aeromonas hydrophila
90       Aeromonas hydrophila
91       Aeromonas hydrophila

                                              Article Full Sequence
0   Computational characterization of epitopic reg...     IKKYEPAPV
1   Computational characterization of epitopic reg...     YGPNYKWKF
2   Computational characterization of epitopic reg...     YGPNYKWKF
3   Computational characterization of epitopic reg...     YGPNYKWKF
4   Computational characterization of epitopic reg...     YGPNYKWKF
..                                                ...           ...
87  The Screening of the Protective Antigens of Ae...           NaN
88  The Screening of the Protective Antigens of Ae...           NaN
89  The Screening of the Protective Antigens of Ae...           NaN
90  The Screening of the Protective Antigens of Ae...           NaN
91  The Screening of the Protective Antigens of Ae...           NaN

[92 rows x 6 columns]

In [19]:
df_vaccine_candidate

,Protien Number,Sequences,Protien Description,Species,Article,Full Sequence
0,WP_014165385,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,IKKYEPAPV
1,WP_107317750,MKKILALFSLFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
2,WP_195157289,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
3,WP_065213479,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
4,WP_105196548,MKKLLTLFSLFLCAEQIQAQSYIGFVPDNYSGVHGMIYNPAAIVGS...,MULTISPECIES: DUF5723 family protein [Flavobac...,Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF
5,WP_097609673,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,DUF5723 family protein [Flavobacterium columnare],Flavobacterium columnare,Computational characterization of epitopic reg...,YGPNYKWKF

In [24]:
import pandas as pd
from Bio import SeqIO

# List of FASTA file paths
fasta_files = [
    'uniprotkb_Aeromonas_hydrophila_AND_anno_2024_10_30.fasta',
    'uniprotkb_Edwardsiella_ictaluri_AND_ann_2024_10_30.fasta',
    'uniprotkb_Flavobacterium_columnare_AND_2024_10_30.fasta'
]

# Initialize an empty list to collect data
data = []

# Parse each FASTA file and extract Protein Number and Sequence
for file in fasta_files:
    for record in SeqIO.parse(file, 'fasta'):
        # Extract Protein Number from header
        protein_number = record.id.split('|')[1] if '|' in record.id else record.id
        # Extract sequence
        sequence = str(record.seq)
        # Append to data list
        data.append([protein_number, sequence])

# Create a DataFrame from the data list
df_sequences = pd.DataFrame(data, columns=['Protein Number', 'Sequence'])

# Save DataFrame to a CSV file
df_sequences.to_csv('all_sequences.csv', index=False)

# Display the DataFrame
print(df_sequences)

    Protein Number                                           Sequence
0       A0A081UPN5  MSETKTNLLDLDRDAMRAFFVELGEKPFRADQVMKWIYHFGCDDFD...
1       A0A081UQL1  MTKQIKRIGVLTSGGDAPGMNAAIRAVVRAGLHHGLEVYGIYDGYL...
2       A0A0F6KC92  MKKVGLVGWRGMVGSVLMSRMQEEKDFSRIQPTFFTTSQAGEAAPN...
3       A0A0S3BF99  MPKKFYVSWDNLQREARRLARRQLPVSQWKGIIAVSRGGLVPAALM...
4       A0A0T6R2D4  MKKVGLVGWRGMVGSVLMSRMQEEQDFAHIQPTFFTTSQAGEAAPN...
..             ...                                                ...
229         G8X5B7  MTFQNTLAFAQQLDIQDELKNYRSEFIFPQHNEKDVIYFTGNSLGL...
230         G8X607  MSVLSGKKIILGVTGGIAAYKSASLVRLLIKAGAQVQVIMTPASLD...
231         G8X6M6  MNLKDLLYKVAIEAVQGSPIGIVNQIQFDSRKIESDDVFVAIRGTL...
232         G8X951  MKIAVVGATGMVGEVMLQVLAERNFPITELIPVASEKSIGKEIEFK...
233         G8XB63  MLKFILNYSILLFFKKTKMKIVFASNNQNKIKEIQRLIPSNIQILS...

[234 rows x 2 columns]

In [25]:
# Load the new dataset with 48,000+ sequences
fcovae_df = pd.read_csv('fcovae_df_woX.csv')

In [26]:
fcovae_df

             id                                           sequence
0          seq1  MAKKGNRIQVILECTEHKTSGVPGTSRYITTKNKKNTPDRLEIKKF...
1          seq2  MSIETISLSGRKKEVSNKKMTFWESLYLVAIVKGLFTTIRHLFKRK...
2          seq3  MNTKYFDLINQTFYFPQEEFTLSKDHLQFHGIDLMKLVEQYGTPLK...
3          seq4  MPKRNIDFVKSILERVSFDAKLFAKELQKALKILLPYEVEELSSWF...
4          seq5  MPKMKTKSSAKKRFKVTGSGKIKRKHAFKSHILTKKSKKRKLALTH...
...         ...                                                ...
69955  seq69958                MAVREDHNLIIAITKENNKLYYKNCPLYKKKQSKH
69956  seq69959  MSSFEQFNLPKSLQKSLDELKFVSPTPIQEKSFNVIMSGRDVMGIA...
69957  seq69960  MTDEVDEMLNDYFDFPEEVTLAKSGTPLEKIEQLSYHVPNFNTKVN...
69958  seq69961  MLAQEILSESFQLNNNALKSKAYLILGSNFTEFANTKKAKDYFLKS...
69959  seq69962  MYQRLSKFAQKFIKPSIFLKYGFNLSPMYRRSTARVMYISENLKNI...

[69960 rows x 2 columns]

In [27]:
# Rename columns if needed to match ('Protein Number' and 'Sequence')
fcovae_df = fcovae_df.rename(columns={'id': 'Protein Number', 'sequence': 'Sequence'})

# Randomly select 200 sequences from the new dataset
fcovae_sample = fcovae_df.sample(n=200, random_state=42)

# Append the random sample to the existing df_sequences DataFrame
df_sequences = pd.concat([df_sequences, fcovae_sample], ignore_index=True)

In [28]:
df_sequences

    Protein Number                                           Sequence
0       A0A081UPN5  MSETKTNLLDLDRDAMRAFFVELGEKPFRADQVMKWIYHFGCDDFD...
1       A0A081UQL1  MTKQIKRIGVLTSGGDAPGMNAAIRAVVRAGLHHGLEVYGIYDGYL...
2       A0A0F6KC92  MKKVGLVGWRGMVGSVLMSRMQEEKDFSRIQPTFFTTSQAGEAAPN...
3       A0A0S3BF99  MPKKFYVSWDNLQREARRLARRQLPVSQWKGIIAVSRGGLVPAALM...
4       A0A0T6R2D4  MKKVGLVGWRGMVGSVLMSRMQEEQDFAHIQPTFFTTSQAGEAAPN...
..             ...                                                ...
429       seq37519  MENKELKRFLEYISFDLDGVIKQIENYEIVGNYTTKNTILQLNIFE...
430        seq1991  MTHNIKSGVATGDQVQEIFNYAKEKGFALPAVNVVGSSTINGTIET...
431       seq19969  MKDPAFLFYSKDFYEGTRMMLPEERACYIDLLIYQHQNGLIPLDLK...
432       seq25323  MEILTQTWHWAISGALIGLVMLLLTYFGKTFGMSSNLRTICSMTGG...
433       seq61938  MLDWLKHLGKEYPDFWKNYLLQLESPSIKKVALYIETTGLNPSKDK...

[434 rows x 2 columns]

In [29]:
# Add 'Vaccine Candidate' column with default value 0
df_sequences['Vaccine Candidate'] = 0

In [30]:
df_sequences

,Protein Number,Sequence,Vaccine Candidate
0,A0A081UPN5,MSETKTNLLDLDRDAMRAFFVELGEKPFRADQVMKWIYHFGCDDFD...,0
1,A0A081UQL1,MTKQIKRIGVLTSGGDAPGMNAAIRAVVRAGLHHGLEVYGIYDGYL...,0
2,A0A0F6KC92,MKKVGLVGWRGMVGSVLMSRMQEEKDFSRIQPTFFTTSQAGEAAPN...,0
3,A0A0S3BF99,MPKKFYVSWDNLQREARRLARRQLPVSQWKGIIAVSRGGLVPAALM...,0
4,A0A0T6R2D4,MKKVGLVGWRGMVGSVLMSRMQEEQDFAHIQPTFFTTSQAGEAAPN...,0
...,...,...,...
429,seq37519,MENKELKRFLEYISFDLDGVIKQIENYEIVGNYTTKNTILQLNIFE...,0
430,seq1991,MTHNIKSGVATGDQVQEIFNYAKEKGFALPAVNVVGSSTINGTIET...,0
431,seq19969,MKDPAFLFYSKDFYEGTRMMLPEERACYIDLLIYQHQNGLIPLDLK...,0
432,seq25323,MEILTQTWHWAISGALIGLVMLLLTYFGKTFGMSSNLRTICSMTGG...,0
433,seq61938,MLDWLKHLGKEYPDFWKNYLLQLESPSIKKVALYIETTGLNPSKDK...,0

In [31]:
# Select the first two columns and add 'Vaccine Candidate' column with default value 1
df_vaccine_candidate = df_vaccine_candidate[['Protien Number', 'Sequences']]
df_vaccine_candidate['Vaccine Candidate'] = 1

In [33]:
# Rename the 'Sequences' column to 'Sequence' directly in the DataFrame
df_vaccine_candidate.rename(columns={'Sequences': 'Sequence'}, inplace=True)

In [34]:
df_vaccine_candidate

,Protien Number,Sequence,Vaccine Candidate
0,WP_014165385,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,1
1,WP_107317750,MKKILALFSLFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,1
2,WP_195157289,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,1
3,WP_065213479,MKKVLALFSFFLCTEQIEAQSYIGFVPDNYSGVHGMIYNPATVVGS...,1
4,WP_105196548,MKKLLTLFSLFLCAEQIQAQSYIGFVPDNYSGVHGMIYNPAAIVGS...,1
...,...,...,...
87,AJE37222.1,MRDTTQVRAMDDYFHSLLLDDALLLDSSDEPDSAPVIQLQRQPQPV...,1
88,AJE37560.1,MEKVIFKRAALSAAIVAAMLAPGMVLAADEAGPTYAAAASKFYEEG...,1
89,AJE37735.1,MRNLTLLSLGLLAANAAHADLGEIPKQSGWSGFLLGGVNAVSYKSN...,1
90,AJE37742.1,MFKANGKGNAVRLVLSVATVAVLAACSSPQERKMANRGFEYEDARL...,1
91,AJE38071.1,MLKRITLIALLATTTATTLSGCANSDVYSGDVYTKDRAKQVQTVSY...,1

In [36]:
# Rename columns to ensure consistent naming
df_sequences.rename(columns={'Protein Number': 'Protien Number'}, inplace=True)

# Merge the two DataFrames
df_final_sequence = pd.concat([df_sequences, df_vaccine_candidate], ignore_index=True)

# Drop rows with NaN values in the 'Protien Number' column, if any
df_final_sequence = df_final_sequence.dropna(subset=['Protien Number'])

# Check for duplicates in 'Protien Number' after cleaning
duplicates = df_final_sequence[df_final_sequence['Protien Number'].duplicated()]

# Display duplicates if any
if not duplicates.empty:
    print("Duplicate Protein Numbers found:")
    print(duplicates)
else:
    print("No duplicate Protein Numbers found.")

No duplicate Protein Numbers found.

In [37]:
df_final_sequence

,Protien Number,Sequence,Vaccine Candidate
0,A0A081UPN5,MSETKTNLLDLDRDAMRAFFVELGEKPFRADQVMKWIYHFGCDDFD...,0
1,A0A081UQL1,MTKQIKRIGVLTSGGDAPGMNAAIRAVVRAGLHHGLEVYGIYDGYL...,0
2,A0A0F6KC92,MKKVGLVGWRGMVGSVLMSRMQEEKDFSRIQPTFFTTSQAGEAAPN...,0
3,A0A0S3BF99,MPKKFYVSWDNLQREARRLARRQLPVSQWKGIIAVSRGGLVPAALM...,0
4,A0A0T6R2D4,MKKVGLVGWRGMVGSVLMSRMQEEQDFAHIQPTFFTTSQAGEAAPN...,0
...,...,...,...
521,AJE37222.1,MRDTTQVRAMDDYFHSLLLDDALLLDSSDEPDSAPVIQLQRQPQPV...,1
522,AJE37560.1,MEKVIFKRAALSAAIVAAMLAPGMVLAADEAGPTYAAAASKFYEEG...,1
523,AJE37735.1,MRNLTLLSLGLLAANAAHADLGEIPKQSGWSGFLLGGVNAVSYKSN...,1
524,AJE37742.1,MFKANGKGNAVRLVLSVATVAVLAACSSPQERKMANRGFEYEDARL...,1
525,AJE38071.1,MLKRITLIALLATTTATTLSGCANSDVYSGDVYTKDRAKQVQTVSY...,1

In [38]:
# Save df_final_sequence to a CSV file
df_final_sequence.to_csv('df_final_sequence.csv', index=False)